class AppRoutes {
  AppRoutes._();
  static const String splashScreen1 = '/';
  static const String onBoarding = '/onBoarding';
  static const String splashScreen2 = '/splashScreen2';
  static const String phoneRegistration = '/phoneRegistration';
  static const String emailVerification = '/emailVerification';
  static const String phoneVerification = '/phoneVerification';
  static const String login = '/login';
  static const String verificationSuccess = '/verificationSuccess';
  static const String home = '/home';
  static const String service = '/service';
  static const String chatDoctor = '/chatDoctor';
  static const String doctorDetails = '/DoctorDetails';
  static const String conformation = '/Conformation';
  static const String sucessScreen = '/sucessScreen';
  static const String history = '/History';
  static const String chatScreen = '/chatScreen';
  static const String historyEmpty = '/historyEmpty';
  static const String listHospital = '/listHospital';
  static const String detailHospital = '/detailHospital';
  static const String hospitalMaps = '/hospitalMaps';
  static const String medicationRemainder = '/medicationRemainder';
  static const String medicationRemainderEmpty = '/medicationRemainderEmpty';
  static const String detailAboutDrug = '/detailAboutDrug';
  static const String medicationRemainderFill = '/medicationRemainderFill';
  static const String articelList = '/articelList';
  static const String article = '/Article';
  static const String percriptionHistory = '/percriptionHistory';
  static const String healthHistory = '/healthHistory';
  static const String transactions = '/transactions';
  static const String accountSetting = '/accountSetting';
}
